kind: PersistentVolume
apiVersion: v1
metadata:
  name: emojigen-image-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/emojigen-images"