kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: emojigen-image-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: emojigen-image-pv